Done mentor part to Database project
Dev-incubator/DIMS-Core.Double-7 pull request #1
Opened 2021-09-06 20:11 UTC by kuzmiich

Create table script tasks
create procedure to delete task
create views to task & userTrack

2021-09-07 17:31 UTC, PushMeNow requested changes

2021-09-07 17:31 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/DIMS-Core.Database.refactorlog
> +</Operations>
remove this file. it's redundant

2021-09-07 17:31 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +Delete Task WHERE Task.TaskId = @id;
delete from

2021-09-07 17:31 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +EXEC DeleteTask @id;
why do you need this call?

2021-09-07 17:31 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/Tasks.sql
> +    [Description] NTEXT NOT NULL,
nvarchar

2021-09-07 17:31 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +﻿CREATE VIEW [dbo].[vTask]
plural name

2021-09-07 17:41 UTC, kuzmiich commented on DIMS-Core.Database/DIMS-Core.Database/DIMS-Core.Database.refactorlog
> +</Operations>
Deleted

2021-09-07 17:41 UTC, kuzmiich commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +Delete Task WHERE Task.TaskId = @id;
Fixed

2021-09-07 17:41 UTC, kuzmiich commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +EXEC DeleteTask @id;
Deleted

2021-09-07 17:43 UTC, kuzmiich commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +﻿CREATE VIEW [dbo].[vTask]
Fixed

2021-09-08 19:07 UTC, PushMeNow approved these changes

2021-09-08 19:08 UTC, merged