Make first week.
Dev-incubator/DIMS-Core.Double-7 pull request #2
Opened 2021-09-06 20:13 UTC by aces47

Add vUserTask view.
Add stored procedures SetUserTaskAsFail, SetUserTaskAsSuccess.
Add SeedData for TaskState.

2021-09-07 17:31 UTC, PushMeNow requested changes

2021-09-07 17:31 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskState.sql
> +) ON [PRIMARY]
Whole this description is redundant and looks like autogenerated. Remove it. Write only PK description.

2021-09-07 17:31 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserTask.sql
> +GO
Read your task in document. Description of foreign keys must be after column description Why do you need all this ALTER TABLE scripts?

2021-09-07 17:31 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskState.sql
> +﻿CREATE TABLE [dbo].[TaskState](
Plural name

2021-09-07 17:31 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserTask.sql
> +                         [dbo].[TaskState] ON [dbo].[UserTask].[StateId] = [dbo].[TaskState].[StateId]
Format this pls. All columns have to be wrapped on different rows.

2021-09-08 15:00 UTC, aces47 commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskState.sql
> +) ON [PRIMARY]
Fixed

2021-09-08 15:00 UTC, aces47 commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserTask.sql
> +GO
Fixed

2021-09-08 15:45 UTC, kuzmiich commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTrack.sql
> +	[TaskTrackId] [int] PRIMARY KEY IDENTITY(1,1) NOT NULL,
You can add PK to the end of the file. Tell me, if we leave it as

2021-09-08 19:11 UTC, PushMeNow approved these changes

2021-09-08 19:14 UTC, merged