Member Repositories
Dev-incubator/DIMS-Core.Double-7 pull request #5
Opened 2021-09-16 20:19 UTC by aces47

Make Repositories for member part of DIMS project

2021-09-17 17:06 UTC, PushMeNow requested changes

2021-09-17 17:06 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            RepositoryException.IsEntityExists(objectFromDB, nameof(objectFromDB));
I'm not recomend call here nameof(objectFromDB) because it is not give us any information. I advise to get type of entity and call FullName property.

2021-09-17 17:06 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/TaskStateRepository.cs
> +        public Task SetUserTaskAsSuccess(int userId,int taskId)
formatting

2021-09-17 17:06 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/TaskStateRepository.cs
> +        public TaskStateRepository(DbContext context) : base(context) { _database = GetDb(); }
Don't inline pls...

2021-09-17 17:06 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/VUserProfileRepository.cs
> +        public VUserProfileRepository(DimsCoreContext context):base(context)
formatting

2021-09-17 17:06 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Identity/DIMS-Core.Identity.csproj
> +        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.9" />
?

2021-09-18 10:13 UTC, aces47 commented on DIMS-Core/DIMS-Core.Common/Exceptions/ObjectNotFoundException.cs
> +    class ObjectNotFoundException : BaseException
Fixed

2021-09-18 10:13 UTC, aces47 commented on DIMS-Core/DIMS-Core.Common/Exceptions/RepositoryException.cs
> +            if(id<=0)
Fixed

2021-09-18 10:14 UTC, aces47 commented on DIMS-Core/DIMS-Core.DataAccessLayer/DIMS-Core.DataAccessLayer.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.9" />
Fixed. I don't know why version has changed. I wasn't updating any packages.

2021-09-18 10:15 UTC, aces47 commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/DimsCoreContext.cs
> +        }
Removed

2021-09-18 10:15 UTC, aces47 commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/ReadOnlyRepository.cs
> +    public class ReadOnlyRepository<TEntity> : IReadOnlyRepository<TEntity>
Fixed

2021-09-18 10:15 UTC, aces47 commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/ReadOnlyRepository.cs
> +        }
Fixed

2021-09-18 10:15 UTC, aces47 commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            RepositoryException.IsEntityExists(objectFromDB, nameof(objectFromDB));
Fixed

2021-09-18 10:15 UTC, aces47 commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/TaskStateRepository.cs
> +        public Task SetUserTaskAsSuccess(int userId,int taskId)
Fixed

2021-09-18 10:15 UTC, aces47 commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/TaskStateRepository.cs
> +        public TaskStateRepository(DbContext context) : base(context) { _database = GetDb(); }
Fixed

2021-09-18 10:15 UTC, aces47 commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/VUserProfileRepository.cs
> +        public VUserProfileRepository(DimsCoreContext context):base(context)
Fixed

2021-09-18 10:15 UTC, aces47 commented on DIMS-Core/DIMS-Core.Identity/DIMS-Core.Identity.csproj
> +        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.9" />
Fixed

2021-09-18 21:15 UTC, PushMeNow approved these changes

2021-09-20 10:16 UTC, aces47 commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/ReadOnlyRepository.cs
> +        public void Dispose()
it's pointless. Nothing changes.

2021-09-20 10:18 UTC, kuzmiich approved these changes

2021-09-21 16:58 UTC, merged