Create unit tests to repository and view repository
Dev-incubator/DIMS-Core.Double-7 pull request #7
Opened 2021-09-21 18:42 UTC by kuzmiich

Create TestContext for view repository tests
Added base infrastructure to unit testing
Added unit tests to view repository & repository

2021-09-22 19:53 UTC, PushMeNow requested changes

2021-09-22 19:53 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/DirectionRepositoryTests.cs
> +        private readonly DirectionRepositoryFixture _repositoryFixture;
Why do you need this renaming?

2021-09-22 19:53 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/DirectionRepositoryTests.cs
> +            await Assert.ThrowsAsync<ObjectNotFoundException>(() => _repositoryFixture.Repository.GetById(id));
Wait why here is ObjectNotFoundException?

2021-09-22 19:53 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/Fixtures/Base/RepositoryFixture.cs
> +        public TRepository Repository => _repository ??= CreateRepository();
I don't see the reason why should you create private field for Repository prop. You can use autoproperty function.

2021-09-22 19:53 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/Fixtures/Base/RepositoryFixture.cs
> +        protected abstract Task InitDatabase();
How are you planing async method in constructor?

2021-09-22 19:53 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/Fixtures/TaskRepositoryFixture.cs
> +        }
Hm... Why do you need this overriding?

2021-09-22 19:53 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/Fixtures/TaskRepositoryFixture.cs
> +    public class TaskRepositoryFixture : RepositoryFixture<TaskRepository>, IDisposable
RepositoryFixture already has IDisposable interface

2021-09-22 19:53 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/Fixtures/VTaskRepositoryFixture.cs
> +        public void Dispose() => Context.Dispose();
??

2021-09-22 19:53 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/Fixtures/Base/RepositoryFixture.cs
> +        private readonly ContextCreator _creator = new ();
Why do you need instanse of this class?

2021-09-22 19:53 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/Infrastructure/ContextCreator.cs
> +    public class ContextCreator
static

2021-09-22 19:53 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/Infrastructure/IContextCreator.cs
> +    public interface IContextCreator<T> where T : DbContext
Why do you need this interface?

2021-09-22 20:05 UTC, kuzmiich commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/ViewTestContext.cs
> +    public class ViewTestContext : DimsCoreContext
fixed

2021-09-22 20:10 UTC, kuzmiich commented on DIMS-Core/DIMS-Core.Tests/Repositories/DirectionRepositoryTests.cs
> +        private readonly DirectionRepositoryFixture _repositoryFixture;
fixed

2021-09-22 20:10 UTC, kuzmiich commented on DIMS-Core/DIMS-Core.Tests/Repositories/DirectionRepositoryTests.cs
> +            await Assert.ThrowsAsync<ObjectNotFoundException>(() => _repositoryFixture.Repository.GetById(id));
revert

2021-09-22 20:16 UTC, kuzmiich commented on DIMS-Core/DIMS-Core.Tests/Repositories/Fixtures/Base/RepositoryFixture.cs
> +        public TRepository Repository => _repository ??= CreateRepository();
fixed

2021-09-22 20:18 UTC, kuzmiich commented on DIMS-Core/DIMS-Core.Tests/Repositories/Fixtures/Base/RepositoryFixture.cs
> +        protected abstract Task InitDatabase();
forgot to remove part of the test case. Fixed

2021-09-24 12:28 UTC, aces47 approved these changes
Good job

2021-09-24 20:07 UTC, PushMeNow requested changes

2021-09-24 20:07 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/Fixtures/Base/RepositoryFixture.cs
> +        public TRepository Repository => CreateRepository();
Here arrow property is useless because you can call this prop twice and repo will be create twice too so better to use autoprop here.

2021-09-24 20:07 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/Fixtures/TaskRepositoryFixture.cs
> +        protected override async void InitDatabase()
async??

2021-09-24 20:07 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/TaskRepositoryTests.cs
> +                                                 .ToArrayAsync();
formatting

2021-09-24 20:07 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/Repositories/VUserTrackRepositoryTests.cs
> +                                    .ToArray();
formatting

2021-09-25 20:02 UTC, PushMeNow approved these changes

2021-09-25 20:02 UTC, merged