Made Services and Tests
Dev-incubator/DIMS-Core.Double-7 pull request #8
Opened 2021-09-25 20:37 UTC by aces47

2021-09-25 21:29 UTC, kuzmiich commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/UserService.cs
> +            var result = await _unitOfWork.SignInManager.PasswordSignInAsync(model.Email,
Bad naming

2021-09-25 21:29 UTC, kuzmiich commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/UserService.cs
> +            var result = await _unitOfWork.UserManager.CreateAsync(mappedEntity, model.Password);
bad naming

2021-09-27 12:03 UTC, aces47 commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/UserService.cs
> +            var result = await _unitOfWork.SignInManager.PasswordSignInAsync(model.Email,
Where?

2021-09-27 12:03 UTC, aces47 commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/UserService.cs
> +            var result = await _unitOfWork.UserManager.CreateAsync(mappedEntity, model.Password);
Where?

2021-09-28 17:42 UTC, PushMeNow requested changes

2021-09-29 13:23 UTC, aces47 commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IReadOnlyService.cs
> +        Task<IEnumerable<TModel>> GetAll();
Fixed

2021-09-29 13:23 UTC, aces47 commented on DIMS-Core/DIMS-Core.BusinessLayer/Models/UserProfileModel.cs
> +        }
Deleted

2021-09-29 13:24 UTC, aces47 commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/IdentityService.cs
> +        protected readonly IIdentityUnitOfWork _unitOfWork;
Fixed

2021-09-29 18:48 UTC, PushMeNow requested changes

2021-09-29 18:48 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Models/UserProfileModel.cs
> -        // You have to implement operator != by comparing First and Last names
Return this TODO back.

2021-09-30 13:48 UTC, aces47 commented on DIMS-Core/DIMS-Core.BusinessLayer/Models/UserProfileModel.cs
> -        // You have to implement operator != by comparing First and Last names
return TODO to UserProfileModel

2021-10-01 20:05 UTC, kuzmiich approved these changes

2021-10-01 20:07 UTC, merged